### ISSUE TITLE
AttributeError: 'S3Hook' object has no attribute 'connection'

### ISSUE THREAD

**Issue by wagnerbsouza** [airflow-plugins/mssql_plugin#2]
Hey everyone!
First of all, I'd like to say thanks for the great job with this and other plugins!
I'm trying to use it to my DAG and apparently that 'connection' attribute doesn't exist in the 'S3Hook' object (anymore?). As well as the 'close' method.

https://github.com/airflow-plugins/mssql_plugin/blob/99894f1c270644f679777e80aefa0a1b6668c38c/operators/mssql_to_s3_operator.py#L288

I've been looking at both https://airflow.apache.org/_modules/airflow/hooks/S3_hook.html and https://airflow.readthedocs.io/en/stable/_modules/airflow/contrib/hooks/aws_hook.html

I noticed that 's3_conn_id' is not in the hook anymore.

https://github.com/airflow-plugins/mssql_plugin/blob/99894f1c270644f679777e80aefa0a1b6668c38c/operators/mssql_to_s3_operator.py#L270

That one I changed to 'aws_conn_id' myself and got it working fine.

I saw these two points in other plugins in airflow-plugins too.

Am I missing something or the codes got a bit outdated?

**Comment by wagnerbsouza** [comment]
Apparently there is a PR for it already at https://github.com/airflow-plugins/mssql_plugin/pull/1

**Comment by elburro1887** [comment]
Would be good if the PR https://github.com/airflow-plugins/mssql_plugin/pull/1  got merged.

This fixes the following error I received, in case anyone else encounters it (using Airflow 2.2.0) :



```Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/mssql_plugin/operators/mssql_to_s3_operator.py", line 91, in execute
    self.build_fetch_query(hook)
  File "/opt/airflow/plugins/mssql_plugin/operators/mssql_to_s3_operator.py", line 160, in build_fetch_query
    self.get_records_all(hook, query_filter)
  File "/opt/airflow/plugins/mssql_plugin/operators/mssql_to_s3_operator.py", line 177, in get_records_all
    self.s3_upload(results)
  File "/opt/airflow/plugins/mssql_plugin/operators/mssql_to_s3_operator.py", line 270, in s3_upload
    s3 = S3Hook(s3_conn_id=self.s3_conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 127, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 's3_conn_id'
